name: flutter_application_1
description: "DATN"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  mqtt_client: ^10.5.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  fl_chart: ^0.70.0
  flutter_local_notifications: ^22.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true